services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catastro-gis
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-django-insecure-change-me}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-false}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,51.92.198.125}
      DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS:-}
      DJANGO_SECURE_SSL_REDIRECT: ${DJANGO_SECURE_SSL_REDIRECT:-false}
      DB_NAME: ${DB_NAME:-catastro}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      GDAL_LIBRARY_PATH: ${GDAL_LIBRARY_PATH:-/usr/lib/x86_64-linux-gnu/libgdal.so}
    volumes:
      - .:/app
    working_dir: /app/backend
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000

  db:
    env_file:
      - .env
    image: postgis/postgis:16-3.4
    container_name: postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-catastro}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: