# Generated by Django 6.1 on 2026-08-11 19:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_codigo', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('local_id', models.CharField(max_length=50)),
                ('referencia_catastral', models.CharField(db_index=True, max_length=20, unique=True)),
                ('etiqueta', models.CharField(blank=True, max_length=50)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('fecha_alta', models.CharField(blank=True, max_length=50)),
                ('geom_25830', django.contrib.gis.db.models.fields.GeometryField(srid=25830)),
                ('geom_4326', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
