# Generated by Django 6.1 on 2026-08-11 12:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='municipio_codigo',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=25830),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='local_id',
            field=models.CharField(max_length=50),
        ),
    ]
